# Generated by Django 4.2.2 on 2024-03-11 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionMaterias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(default='A', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_asistencia', models.IntegerField(default=0)),
                ('minimo_asistencia', models.IntegerField(default=80)),
                ('estado', models.CharField(default='A', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('estado', models.CharField(default='A', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('estado', models.CharField(default='A', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.BinaryField()),
                ('cedula', models.CharField(max_length=15)),
                ('nombres', models.CharField(max_length=75)),
                ('apellidos', models.CharField(max_length=100)),
                ('clave', models.CharField(max_length=20)),
                ('edad', models.IntegerField()),
                ('genero', models.CharField(max_length=50)),
                ('pais_natal', models.CharField(max_length=70)),
                ('ciuda_natal', models.CharField(max_length=100)),
                ('estado', models.CharField(default='A', max_length=3)),
                ('id_perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrativa.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='AulaVirutal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('aprobado', models.CharField(default='-', max_length=50)),
                ('estado', models.CharField(default='A', max_length=3)),
                ('id_asignacion_materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrativa.asignacionmaterias')),
                ('id_asistencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrativa.asistencia')),
                ('id_estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrativa.usuarios')),
            ],
        ),
        migrations.AddField(
            model_name='asignacionmaterias',
            name='id_materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrativa.materia'),
        ),
        migrations.AddField(
            model_name='asignacionmaterias',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrativa.usuarios'),
        ),
    ]
