# Generated by Django 5.0.4 on 2024-04-13 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('curso', models.CharField(max_length=75)),
                ('estado', models.CharField(default='A', max_length=3)),
            ],
        ),
    ]
